services:
  backend:
    build: .
    container_name: backend
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - .:/app
    networks:
      - devhub-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "0.0.0.0:5173:5173"
    networks:
      - devhub-network
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

networks:
  devhub-network:
    driver: bridge
